import React, {FC} from 'react';
// Hooks
// import {useRequest} from 'lib/hooks';
import {
  Theme,
  FormControl,
  Select,
  withStyles,
  MenuItem,
  InputBase,
  InputLabel,
} from '@material-ui/core';
// import {COUNTRIES} from 'lib/constants/endpoints';
const country_list = [
  {
    id: 1,
    name: 'Afghanistan',
  },
  {id: 2, name: 'Aland Islands'},
  {id: 3, name: 'Albania'},
  {id: 4, name: 'Algeria'},
  {id: 5, name: 'American Samoa'},
  {id: 6, name: 'Andorra'},
  {id: 7, name: 'Angola'},
  {id: 8, name: 'Anguilla'},
  {id: 9, name: 'Antarctica'},
  {id: 10, name: 'Antigua and Barbuda'},
  {id: 11, name: 'Argentina'},
  {id: 12, name: 'Armenia'},
  {id: 13, name: 'Aruba'},
  {id: 14, name: 'Australia'},
  {id: 15, name: 'Austria'},
  {id: 16, name: 'Azerbaijan'},
  {id: 17, name: 'Bahamas'},
  {id: 18, name: 'Bahrain'},
  {id: 19, name: 'Bangladesh'},
  {id: 20, name: 'Barbados'},
  {id: 21, name: 'Belarus'},
  {id: 22, name: 'Belgium'},
  {id: 23, name: 'Belize'},
  {id: 24, name: 'Benin'},
  {id: 25, name: 'Bermuda'},
  {id: 26, name: 'Bhutan'},
  {id: 27, name: 'Bolivia'},
  {id: 28, name: 'Bonaire, Sint Eustatius and Saba'},
  {id: 29, name: 'Bosnia and Herzegovina'},
  {id: 30, name: 'Botswana'},
  {id: 31, name: 'Bouvet Island'},
  {id: 32, name: 'Brazil'},
  {id: 33, name: 'British Indian Ocean Territory'},
  {id: 34, name: 'Brunei Darussalam'},
  {id: 35, name: 'Bulgaria'},
  {id: 36, name: 'Burkina Faso'},
  {id: 37, name: 'Burundi'},
  {id: 38, name: 'Cambodia'},
  {id: 39, name: 'Cameroon'},
  {id: 40, name: 'Canada'},
  {id: 41, name: 'Cape Verde'},
  {id: 42, name: 'Cayman Islands'},
  {id: 43, name: 'Central African Republic'},
  {id: 44, name: 'Chad'},
  {id: 45, name: 'Chile'},
  {id: 46, name: 'China'},
  {id: 47, name: 'Christmas Island'},
  {id: 48, name: 'Cocos (Keeling) Islands'},
  {id: 49, name: 'Colombia'},
  {id: 50, name: 'Comoros'},
  {id: 51, name: 'Congo'},
  {id: 52, name: 'Congo, The Democratic Republic of'},
  {id: 53, name: 'Cook Islands'},
  {id: 54, name: 'Costa Rica'},
  {id: 55, name: "Cote d'Ivoire"},
  {id: 56, name: 'Croatia'},
  {id: 57, name: 'Cuba'},
  {id: 58, name: 'CuraÃ§ao'},
  {id: 59, name: 'Cyprus'},
  {id: 60, name: 'Czechia'},
  {id: 61, name: 'Denmark'},
  {id: 62, name: 'Djibouti'},
  {id: 63, name: 'Dominica'},
  {id: 64, name: 'Dominican Republic'},
  {id: 65, name: 'Ecuador'},
  {id: 66, name: 'Egypt'},
  {id: 67, name: 'El Salvador'},
  {id: 68, name: 'Equatorial Guinea'},
  {id: 69, name: 'Eritrea'},
  {id: 70, name: 'Estonia'},
  {id: 71, name: 'Ethiopia'},
  {id: 72, name: 'Falkland Islands (Malvinas)'},
  {id: 73, name: 'Faroe Islands'},
  {id: 74, name: 'Fiji'},
  {id: 75, name: 'Finland'},
  {id: 76, name: 'France'},
  {id: 77, name: 'French Guiana'},
  {id: 78, name: 'French Polynesia'},
  {id: 79, name: 'French Southern Territories'},
  {id: 80, name: 'Gabon'},
  {id: 81, name: 'Gambia'},
  {id: 82, name: 'Georgia'},
  {id: 83, name: 'Germany'},
  {id: 84, name: 'Ghana'},
  {id: 85, name: 'Gibraltar'},
  {id: 86, name: 'Greece'},
  {id: 87, name: 'Greenland'},
  {id: 88, name: 'Grenada'},
  {id: 89, name: 'Guadeloupe'},
  {id: 90, name: 'Guam'},
  {id: 91, name: 'Guatemala'},
  {id: 92, name: 'Guernsey'},
  {id: 93, name: 'Guinea'},
  {id: 94, name: 'Guinea-Bissau'},
  {id: 95, name: 'Guyana'},
  {id: 96, name: 'Haiti'},
  {id: 97, name: 'Heard and Mc Donald Islands'},
  {id: 98, name: 'Holy See (Vatican City State)'},
  {id: 99, name: 'Honduras'},
  {id: 100, name: 'Hong Kong'},
  {id: 101, name: 'Hungary'},
  {id: 102, name: 'Iceland'},
  {id: 103, name: 'India'},
  {id: 104, name: 'Indonesia'},
  {id: 105, name: 'Iran, Islamic Republic of'},
  {id: 106, name: 'Iraq'},
  {id: 107, name: 'Ireland'},
  {id: 108, name: 'Isle of Man'},
  {id: 109, name: 'Israel'},
  {id: 110, name: 'Italy'},
  {id: 111, name: 'Jamaica'},
  {id: 112, name: 'Japan'},
  {id: 113, name: 'Jersey'},
  {id: 114, name: 'Jordan'},
  {id: 115, name: 'Kazakstan'},
  {id: 116, name: 'Kenya'},
  {id: 117, name: 'Kiribati'},
  {id: 118, name: "Korea, Democratic People's Republic of"},
  {id: 119, name: 'Korea, Republic of'},
  {id: 120, name: 'Kosovo (temporary code)'},
  {id: 121, name: 'Kuwait'},
  {id: 122, name: 'Kyrgyzstan'},
  {id: 123, name: "Lao, People's Democratic Republic"},
  {id: 124, name: 'Latvia'},
  {id: 125, name: 'Lebanon'},
  {id: 126, name: 'Lesotho'},
  {id: 127, name: 'Liberia'},
  {id: 128, name: 'Libyan Arab Jamahiriya'},
  {id: 129, name: 'Liechtenstein'},
  {id: 130, name: 'Lithuania'},
  {id: 131, name: 'Luxembourg'},
  {id: 132, name: 'Macao'},
  {id: 133, name: 'Macedonia, The Former Yugoslav Republic Of'},
  {id: 134, name: 'Madagascar'},
  {id: 135, name: 'Malawi'},
  {id: 136, name: 'Malaysia'},
  {id: 137, name: 'Maldives'},
  {id: 138, name: 'Mali'},
  {id: 139, name: 'Malta'},
  {id: 140, name: 'Marshall Islands'},
  {id: 141, name: 'Martinique'},
  {id: 142, name: 'Mauritania'},
  {id: 143, name: 'Mauritius'},
  {id: 144, name: 'Mayotte'},
  {id: 145, name: 'Mexico'},
  {id: 146, name: 'Micronesia, Federated States of'},
  {id: 147, name: 'Moldova, Republic of'},
  {id: 148, name: 'Monaco'},
  {id: 149, name: 'Mongolia'},
  {id: 150, name: 'Montenegro'},
  {id: 151, name: 'Montserrat'},
  {id: 152, name: 'Morocco'},
  {id: 153, name: 'Mozambique'},
  {id: 154, name: 'Myanmar'},
  {id: 155, name: 'Namibia'},
  {id: 156, name: 'Nauru'},
  {id: 157, name: 'Nepal'},
  {id: 158, name: 'Netherlands'},
  {id: 159, name: 'Netherlands Antilles'},
  {id: 160, name: 'New Caledonia'},
  {id: 161, name: 'New Zealand'},
  {id: 162, name: 'Nicaragua'},
  {id: 163, name: 'Niger'},
  {id: 164, name: 'Nigeria'},
  {id: 165, name: 'Niue'},
  {id: 166, name: 'Norfolk Island'},
  {id: 167, name: 'Northern Mariana Islands'},
  {id: 168, name: 'Norway'},
  {id: 169, name: 'Oman'},
  {id: 170, name: 'Pakistan'},
  {id: 171, name: 'Palau'},
  {id: 172, name: 'Palestinian Territory, Occupied'},
  {id: 173, name: 'Panama'},
  {id: 174, name: 'Papua New Guinea'},
  {id: 175, name: 'Paraguay'},
  {id: 176, name: 'Peru'},
  {id: 177, name: 'Philippines'},
  {id: 178, name: 'Pitcairn'},
  {id: 179, name: 'Poland'},
  {id: 180, name: 'Portugal'},
  {id: 181, name: 'Puerto Rico'},
  {id: 182, name: 'Qatar'},
  {id: 183, name: 'Republic of Serbia'},
  {id: 184, name: 'Reunion'},
  {id: 185, name: 'Romania'},
  {id: 186, name: 'Russia Federation'},
  {id: 187, name: 'Rwanda'},
  {id: 188, name: 'Saint BarthÃ©lemy'},
  {id: 189, name: 'Saint Helena'},
  {id: 190, name: 'Saint Kitts & Nevis'},
  {id: 191, name: 'Saint Lucia'},
  {id: 192, name: 'Saint Martin'},
  {id: 193, name: 'Saint Pierre and Miquelon'},
  {id: 194, name: 'Saint Vincent and the Grenadines'},
  {id: 195, name: 'Samoa'},
  {id: 196, name: 'San Marino'},
  {id: 197, name: 'Sao Tome and Principe'},
  {id: 198, name: 'Saudi Arabia'},
  {id: 199, name: 'Senegal'},
  {id: 200, name: 'Serbia and Montenegro'},
  {id: 201, name: 'Seychelles'},
  {id: 202, name: 'Sierra Leone'},
  {id: 203, name: 'Singapore'},
  {id: 204, name: 'Sint Maarten'},
  {id: 205, name: 'Slovakia'},
  {id: 206, name: 'Slovenia'},
  {id: 207, name: 'Solomon Islands'},
  {id: 208, name: 'Somalia'},
  {id: 209, name: 'South Africa'},
  {id: 210, name: 'South Georgia & The South Sandwich Islands'},
  {id: 211, name: 'South Sudan'},
  {id: 212, name: 'Spain'},
  {id: 213, name: 'Sri Lanka'},
  {id: 214, name: 'Sudan'},
  {id: 215, name: 'Suriname'},
  {id: 216, name: 'Svalbard and Jan Mayen'},
  {id: 217, name: 'Swaziland'},
  {id: 218, name: 'Sweden'},
  {id: 219, name: 'Switzerland'},
  {id: 220, name: 'Syrian Arab Republic'},
  {id: 221, name: 'Taiwan, Province of China'},
  {id: 222, name: 'Tajikistan'},
  {id: 223, name: 'Tanzania, United Republic of'},
  {id: 224, name: 'Thailand'},
  {id: 225, name: 'Timor-Leste'},
  {id: 226, name: 'Togo'},
  {id: 227, name: 'Tokelau'},
  {id: 228, name: 'Tonga'},
  {id: 229, name: 'Trinidad and Tobago'},
  {id: 230, name: 'Tunisia'},
  {id: 231, name: 'Turkey'},
  {id: 232, name: 'Turkish Rep N Cyprus (temporary code)'},
  {id: 233, name: 'Turkmenistan'},
  {id: 234, name: 'Turks and Caicos Islands'},
  {id: 235, name: 'Tuvalu'},
  {id: 236, name: 'Uganda'},
  {id: 237, name: 'Ukraine'},
  {id: 238, name: 'United Arab Emirates'},
  {id: 239, name: 'United Kingdom'},
  {id: 240, name: 'United States'},
  {id: 241, name: 'United States Minor Outlying Islands'},
  {id: 242, name: 'Uruguay'},
  {id: 243, name: 'Uzbekistan'},
  {id: 244, name: 'Vanuatu'},
  {id: 245, name: 'Venezuela'},
  {id: 246, name: 'Vietnam'},
  {id: 247, name: 'Virgin Islands, British'},
  {id: 248, name: 'Virgin Islands, U.S.'},
  {id: 249, name: 'Wallis and Futuna'},
  {id: 250, name: 'Western Sahara'},
  {id: 251, name: 'Yemen'},
  {id: 252, name: 'Zambia'},
  {id: 253, name: 'Zimbabwe'},
];

const StyledSelectInput = withStyles((theme: Theme) => ({
  root: {
    'label + &': {
      marginTop: theme.spacing(3),
      width: '100%',
    },
    borderRadius: 4,
    border: '1px solid #ced4da',
    '&.Mui-error': {
      borderColor: 'red',
    },
  },
  input: {
    width: '100%',
    borderRadius: 4,
    position: 'relative',
    backgroundColor: theme.palette.background.paper,
    fontSize: 16,
    padding: '10px 26px 10px 12px',
    transition: theme.transitions.create(['border-color', 'box-shadow']),
    '&:focus': {
      borderRadius: 4,
      borderColor: '#80bdff',
      boxShadow: '0 0 0 0.2rem rgba(0,123,255,.25)',
    },
  },
}))(InputBase);

export interface ICountrySelectorProps {
  handleCountry: (event: any) => void;
  value: string;
  error: boolean;
}

const CountrySelector: FC<ICountrySelectorProps> = (props) => {
  // props speading
  const {handleCountry, error} = props;
  // const {data: country_list}: any = useRequest({
  //   url: COUNTRIES,
  // });
  // if (!country_list) {
  //   return <>loading</>;
  // }
  return (
    <>
      <FormControl className="inputForm">
        <InputLabel shrink id="demo-customized-select-label">
          Country
        </InputLabel>
        <Select
          {...props}
          error={error}
          labelId="demo-customized-select-label"
          id="demo-customized-select"
          onChange={handleCountry}
          displayEmpty
          input={<StyledSelectInput />}
        >
          <MenuItem value="">Select Country</MenuItem>
          {country_list.map((option: any, index: any) => (
            <MenuItem key={index} value={option.id}>
              {option.name}
            </MenuItem>
          ))}
        </Select>
      </FormControl>
    </>
  );
};
export default CountrySelector;
